### ISSUE TITLE
Copying any tag crashes the app immediately (OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))

### ISSUE THREAD

**Issue by Drakonas** [nostrenz/hatate-iqdb-tagger#21]
I am using Windows 11 21H2 and Release 12 of Hatate.

It would seem the method used to access the clipboard fails. I am unable to test if this affects other versions of Windows.

```
System.Windows.Threading.DispatcherUnhandledExceptionEventArgs
OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
mscorlib
System.Collections.ListDictionaryInternal
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at System.Windows.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Clipboard.SetText(String text)
   at Hatate.App.CopySelectedTagsToClipboard(ListBox from)
   at Hatate.MainWindow.<ContextMenu_MenuItem_Click>d__110.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at System.Windows.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Clipboard.SetText(String text)
   at Hatate.App.CopySelectedTagsToClipboard(ListBox from)
   at Hatate.MainWindow.<ContextMenu_MenuItem_Click>d__110.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by nostrenz** [comment]
Hi, I've never noticed a problem with the clipboard on previous versions of Windows (tried both on Windows 10 as well as Windows 8) so I guess it's specific to Windows 11.

I made a build to try various alternative methods, when copying something it should display a small window with a message like "(X) works" telling which one (if any) worked. Can you try it to see if it works? [Hatate-clipboard.zip](https://github.com/nostrenz/hatate-iqdb-tagger/files/9456690/Hatate-clipboard.zip)
